### ISSUE TITLE
Add google map and marker drag & drop feature to FrontEnd

### ISSUE THREAD

**Issue by agorshechnikov** [intelliants/subrion-plugin-gmap#7]
There is no google map and marker drag & drop feature on FrontEnd -> Edit listing but in Admin Panel they exist.
![map-and-marker](https://cloud.githubusercontent.com/assets/15151937/25079281/da80f456-235c-11e7-9420-0d745e5d2c41.png)

**Comment by ghost** [comment]
Fixed in https://github.com/intelliants/subrion-plugin-gmap/commit/928b9f05813cca0f634202d59d1053615d689a6d

**Comment by CKENT0369** [comment]
Not fixed - Uninstalled google map, cleared cache, deleted all files on server. Uploaded changed files you provide in 928b9f0, Installed google map plugin, go to settings get "No Implemented Packages"
![gmapsettings](https://user-images.githubusercontent.com/11754368/31641102-82423852-b2b0-11e7-87e6-0f060ee8ae17.JPG)

**Comment by vbezruchkin** [comment]
Hi @CKENT0369 

I believe the issue is fixed for the latest version of our core system which is available in repository :( We will recheck if it's possible to apply these fixes for an older core version.

Please clarify which one you have.

Thanks

**Comment by CKENT0369** [comment]
The above issue is resolved but it still does not show the pins for the members on the the map block on front end. Also is there a way to choose the map center and zoom level like there use to be?

**Comment by agorshechnikov** [comment]
Issue exists for Registration page, i.e. if member fills the location fields: Country, ZIP, City, State and Address during registration process then Lat & Lng columns are empty.

**Comment by vbezruchkin** [comment]
There is no easy way to fetch coordinates on registration page as it does not use common JS. This could be implemented as a custom modification for a specific customer. Sorry, no plans to implement this in our default functionality.
